### PR TITLE
Supporting CakePHP 2.7

### PR DESCRIPTION
**Pull request by okinaka**
refs #101

### CODE REVIEW

**Comment by steinkel** [comment]
We should keep BC with CakePHP < 2.7
Could you use a custom validation rule instead?

Thank you!

**Comment by okinaka** [comment]
Done.

**Comment by okinaka** [comment]
@steinkel  I update this PR to support custom validation.

**Comment by okinaka** [comment]
@steinkel ping

**Comment by steinkel** [comment]
Thank you @okinaka

**Pull request merged**
